// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/ingester.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngesterPlugin_Start_FullMethodName = "/dstream.IngesterPlugin/Start"
)

// IngesterPluginClient is the client API for IngesterPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This is the plugin interface every Ingester plugin must implement.
type IngesterPluginClient interface {
	// Starts the plugin and begins streaming events back to the CLI
	Start(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type ingesterPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewIngesterPluginClient(cc grpc.ClientConnInterface) IngesterPluginClient {
	return &ingesterPluginClient{cc}
}

func (c *ingesterPluginClient) Start(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngesterPlugin_ServiceDesc.Streams[0], IngesterPlugin_Start_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngesterPlugin_StartClient = grpc.ServerStreamingClient[Event]

// IngesterPluginServer is the server API for IngesterPlugin service.
// All implementations must embed UnimplementedIngesterPluginServer
// for forward compatibility.
//
// This is the plugin interface every Ingester plugin must implement.
type IngesterPluginServer interface {
	// Starts the plugin and begins streaming events back to the CLI
	Start(*StreamRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedIngesterPluginServer()
}

// UnimplementedIngesterPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngesterPluginServer struct{}

func (UnimplementedIngesterPluginServer) Start(*StreamRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedIngesterPluginServer) mustEmbedUnimplementedIngesterPluginServer() {}
func (UnimplementedIngesterPluginServer) testEmbeddedByValue()                        {}

// UnsafeIngesterPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngesterPluginServer will
// result in compilation errors.
type UnsafeIngesterPluginServer interface {
	mustEmbedUnimplementedIngesterPluginServer()
}

func RegisterIngesterPluginServer(s grpc.ServiceRegistrar, srv IngesterPluginServer) {
	// If the following call pancis, it indicates UnimplementedIngesterPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngesterPlugin_ServiceDesc, srv)
}

func _IngesterPlugin_Start_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IngesterPluginServer).Start(m, &grpc.GenericServerStream[StreamRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngesterPlugin_StartServer = grpc.ServerStreamingServer[Event]

// IngesterPlugin_ServiceDesc is the grpc.ServiceDesc for IngesterPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngesterPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dstream.IngesterPlugin",
	HandlerType: (*IngesterPluginServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Start",
			Handler:       _IngesterPlugin_Start_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ingester.proto",
}
