// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DStreamPlugin_Start_FullMethodName = "/plugin.DStreamPlugin/Start"
)

// DStreamPluginClient is the client API for DStreamPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The unified plugin interface for all plugin types (ingester, router, etc.)
type DStreamPluginClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
}

type dStreamPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDStreamPluginClient(cc grpc.ClientConnInterface) DStreamPluginClient {
	return &dStreamPluginClient{cc}
}

func (c *dStreamPluginClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, DStreamPlugin_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DStreamPluginServer is the server API for DStreamPlugin service.
// All implementations must embed UnimplementedDStreamPluginServer
// for forward compatibility.
//
// The unified plugin interface for all plugin types (ingester, router, etc.)
type DStreamPluginServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	mustEmbedUnimplementedDStreamPluginServer()
}

// UnimplementedDStreamPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDStreamPluginServer struct{}

func (UnimplementedDStreamPluginServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedDStreamPluginServer) mustEmbedUnimplementedDStreamPluginServer() {}
func (UnimplementedDStreamPluginServer) testEmbeddedByValue()                       {}

// UnsafeDStreamPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DStreamPluginServer will
// result in compilation errors.
type UnsafeDStreamPluginServer interface {
	mustEmbedUnimplementedDStreamPluginServer()
}

func RegisterDStreamPluginServer(s grpc.ServiceRegistrar, srv DStreamPluginServer) {
	// If the following call pancis, it indicates UnimplementedDStreamPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DStreamPlugin_ServiceDesc, srv)
}

func _DStreamPlugin_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DStreamPluginServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DStreamPlugin_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DStreamPluginServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DStreamPlugin_ServiceDesc is the grpc.ServiceDesc for DStreamPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DStreamPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.DStreamPlugin",
	HandlerType: (*DStreamPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _DStreamPlugin_Start_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin.proto",
}
